### PR TITLE
Upgrading egui library to 0.27.2 to fix epaint conflicts

### PR DESCRIPTION
**Pull request by CtByte**
Upgrading egui library to 0.27.2 to fix epaint conflicts

### CODE REVIEW

**Comment by patrickelectric** [comment]
ping @bernsteining that is important!

**Comment by CtByte** [comment]
I don't know know if there is a better way to ping @bernsteining (I don't use twitter). I would rather not fork this project 😭

**Comment by patrickelectric** [comment]
> I don't know know if there is a better way to ping @bernsteining (I don't use twitter). I would rather not fork this project 😭

I just did: https://x.com/patrickdev_/status/1800513343813554587

**Comment by bernsteining** [comment]
Sorry for the delay, dependencies are bumped with c1dc734777f1f1366f4d89f115a7d6700f6b28a8

Thanks for noticing !

**Pull request closed without merging**
